language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
install:
  - pip install coveralls
  - pip install -e .
import:
  - .hscfg
script:
  - nosetests -v --with-coverage --cover-package=mhkit mhkit    
after_success:
  - coveralls
